N8N_LOGGING_URL = "http://localhost:5678/webhook/ecosense-log"
N8N_ALERTING_URL = "http://localhost:5678/webhook/ecosense-alert"
N8N_VISUALIZATION_URL = "http://localhost:5678/webhook/ecosense-chart"
